name: 👤🎟️

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  pull-requests: write

jobs:
  assign:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Assign repository owner
        uses: actions/github-script@v9
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['r3bo0tbx1']
            });
